
sudo: required
# sudo: false
dist: xenial

language: c++
compiler:
  - clang
  - gcc

# os:
#     - linux


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      # - clang-7.0
      - gcc-7
      # - gcc-8
      - libsdl2-dev
      - libglew-dev
      - libftgl-dev
      - libsoil-dev
      - libgl1-mesa-dev
      - libtar-dev
      - zlib1g-dev

env:
  - COMPILER=clang++-7


# safelist
branches:
  only:
  - master
  - hexmap_qt
  - ogl_compatability
  - travis-ci


# install:

# before_script:

script:
  make -j4 CXX=$COMPILER TRAVIS=1 -f asdf_multiplat/asdf_multiplat.mk && make -j4 CXX=$COMPILER TRAVIS=1 -f hexmap/libhexmap.mk

# after_success:

# after_failure:


notifications:
  email: false