
# sudo: required
sudo: false
dist: trusty

language: c++
compiler: clang
  # - clang
  # - gcc

# os:
#     - linux


addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8

    packages:
      - clang-3.8
      - libsdl2-dev
      - libglew-dev
      - libftgl-dev
      - libsoil-dev
      - libgl1-mesa-dev

env:
  - COMPILER=clang++-3.8
  - TRAVIS=1

before_install:
  # - sudo apt-get update -qq
  # - TODO dependancies

install:
  -

# before_script:

script:
  make CXX=$COMPILER -f asdf_multiplat/asdf_multiplat.mk
  # make  -f hexmap/hexmap.mk

# after_success:

# after_failure:

branches:
  only:
    - travis-ci

notifications:
  email: false