
sudo: required
# sudo: false
dist: xenial

language: c++
compiler: clang
  # - clang
  # - gcc

# os:
#     - linux


addons:
  apt:
    # sources:
      # - ubuntu-toolchain-r-test

    packages:
      - clang-7.0
      # - g++-6
      - libsdl2-dev
      - libglew-dev
      - libftgl-dev
      - libsoil-dev
      - libgl1-mesa-dev
      - libtar-dev

env:
  - COMPILER=clang++-7


# safelist
branches:
  only:
  - master
  - hexmap_qt
  - ogl_compatability
  - travis-ci


# install:

# before_script:

script:
  make -j4 CXX=$COMPILER TRAVIS=1 -f asdf_multiplat/asdf_multiplat.mk && make -j4 CXX=$COMPILER TRAVIS=1 -f hexmap/hexmap.mk

# after_success:

# after_failure:


notifications:
  email: false